# netlify.toml
[build]
  command = "npm install && npm run build"
  publish = ".next"  # مجلد البناء، مختلف عن base directory

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
