[build]
  command = "npm run build"
  publish = ".next"
  functions = ".next/functions"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"