[build]
  command = "npm install && npm run build"
  publish = "/"  # يترك Netlify يحدد مجلد النشر تلقائياً

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"